CC = cl
LDFLAGS = /nologo
LDLIBS = d3d11.lib dxgi.lib dxguid.lib user32.lib gdi32.lib d3dcompiler.lib getopt.lib
SRC_DIR = src
BIN_DIR = bin
TARGET = $(BIN_DIR)\monitor_mirror.exe
SOURCES = $(SRC_DIR)\main.c

all: $(TARGET)

$(TARGET): $(SOURCES) $(BIN_DIR)
	$(CC) $(CFLAGS) $(SOURCES) /Fe$(TARGET) /link $(LDFLAGS) $(LDLIBS)

$(BIN_DIR):
	@if not exist $(BIN_DIR) mkdir $(BIN_DIR)

run: $(TARGET)
	$(TARGET)

clean:
	@if exist $(BIN_DIR) rmdir /s /q $(BIN_DIR)
